fedora_task:
  container:
    matrix:
      - image: fedora:29
      - image: fedora:30
  script:
    - mkdir artifacts
    - cat /etc/os-release | grep PRETTY_NAME | cut -d '"' -f 2 > artifacts/name.txt
  names_artifacts:
    path: "artifacts/*"
